<%@ Page Language="C#"MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="SampleGrid.aspx.cs" Inherits="RestaurantReviewWeb.SampleGrid" %>


 <asp:Content ID="contentPlaceHolderLogin" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
     <div>
         <asp:gridview ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="UserName" AutoGenerateDeleteButton="True"
    AutoGenerateEditButton="True" OnRowCancelingEdit ="RowCancelingEdit"   
                    onrowdeleting="RowDeleting" onrowediting="RowEditing"   
                    onrowupdating="RowUpdating" ShowFooter="true" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"  >
    <Columns>  
                        <asp:TemplateField HeaderText="Id">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtId" runat="server" Text='<%# Bind("Id") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                             <ItemTemplate>  
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("Id") %>'></asp:Label>  
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtNewId" runat="server" ></asp:TextBox>
                            </FooterTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="UserName">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtUserName" runat="server" Text='<%# Bind("UserName") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                             <ItemTemplate>  
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("UserName") %>'></asp:Label>  
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtNewUserName" runat="server" ></asp:TextBox>
                            </FooterTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="Password">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtPassword" runat="server" Text='<%# Bind("Password") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("Password") %>'></asp:Label>  
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtNewPassword" runat="server" ></asp:TextBox>
                            </FooterTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="Role">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtRole" runat="server" Text='<%# Bind("Role") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                             <ItemTemplate>  
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("Role") %>'></asp:Label>  
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtNewRole" runat="server" ></asp:TextBox>
                            </FooterTemplate>
                            </asp:TemplateField>
                       <asp:TemplateField HeaderText="Email">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtEmail" runat="server" Text='<%# Bind("Email") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                           <ItemTemplate>  
                                <asp:Label ID="Label3" runat="server" Text='<%# Bind("Email") %>'></asp:Label>  
                            </ItemTemplate>
                           <FooterTemplate>
                                <asp:TextBox ID="txtNewEmail" runat="server" ></asp:TextBox>
                           </FooterTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="Street">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtStreet" runat="server" Text='<%# Bind("Street") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label4" runat="server" Text='<%# Bind("Street") %>'></asp:Label>  
                            </ItemTemplate>
                            <FooterTemplate>
                                   <asp:TextBox ID="txtNewStreet" runat="server" ></asp:TextBox>
                            </FooterTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="City">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtCity" runat="server" Text='<%# Bind("City") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label5" runat="server" Text='<%# Bind("City") %>'></asp:Label>  
                            </ItemTemplate>
                            <FooterTemplate>
                                 <asp:TextBox ID="txtNewCity" runat="server" ></asp:TextBox>
                            </FooterTemplate>
                            </asp:TemplateField>
                       <asp:TemplateField HeaderText="State">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtState" runat="server" Text='<%# Bind("State") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                           <ItemTemplate>  
                                <asp:Label ID="Label6" runat="server" Text='<%# Bind("State") %>'></asp:Label>  
                            </ItemTemplate>
                           <FooterTemplate>
                               <asp:TextBox ID="txtNewState" runat="server" ></asp:TextBox>
                           </FooterTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="Pincode">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtPincode" runat="server" Text='<%# Bind("Pincode") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label7" runat="server" Text='<%# Bind("Pincode") %>'></asp:Label>  
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtNewPincode" runat="server" ></asp:TextBox>
                            </FooterTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="Country">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtCountry" runat="server" Text='<%# Bind("Country") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label8" runat="server" Text='<%# Bind("Country") %>'></asp:Label>  
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtNewCountry" runat="server" ></asp:TextBox>
                            </FooterTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="PhoneNumber">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtPhoneNumber" runat="server" Text='<%# Bind("PhoneNumber") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label9" runat="server" Text='<%# Bind("PhoneNumber") %>'></asp:Label>  
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtNewPhoneNumber" runat="server" ></asp:TextBox>
                            </FooterTemplate>
                            </asp:TemplateField>

  </Columns>
            
              
</asp:gridview>
        </div>
     <asp:Button ID="btnAdd" runat="server" Text="Add" OnClick="btnAdd_Click"/>
    </asp:Content>

