<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SampleGrid.aspx.cs" Inherits="RestaurantReviewWeb.SampleGrid" %>

<%--<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
    </form>
</body>
</html>--%>
>
<asp:content id="Content" runat="server" contentplaceholderid="linkLogin" runtat="server">
    <div>
<asp:gridview ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" AutoGenerateDeleteButton="True"
    AutoGenerateEditButton="True" onrowcancelingedit="RowCancelingEdit"   
                    onrowdeleting="RowDeleting" onrowediting="RowEditing"   
                    onrowupdating="RowUpdating" >
    <Columns>  
                        <asp:TemplateField HeaderText="UserName">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtUserName" runat="server" Text='<%# Bind("UserName") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                             <ItemTemplate>  
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("UserName") %>'></asp:Label>  
                            </ItemTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="Password">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtPassword" TextMode="Password" runat="server" Text='<%# Bind("Password") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("Password") %>'></asp:Label>  
                            </ItemTemplate>
                            </asp:TemplateField>
                       <asp:TemplateField HeaderText="Email">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtEmail" runat="server" Text='<%# Bind("Email") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                           <ItemTemplate>  
                                <asp:Label ID="Label3" runat="server" Text='<%# Bind("Email") %>'></asp:Label>  
                            </ItemTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="Street">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtStreet" runat="server" Text='<%# Bind("Street") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label4" runat="server" Text='<%# Bind("Street") %>'></asp:Label>  
                            </ItemTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="City">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtCity" runat="server" Text='<%# Bind("City") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label5" runat="server" Text='<%# Bind("City") %>'></asp:Label>  
                            </ItemTemplate>
                            </asp:TemplateField>
                       <asp:TemplateField HeaderText="State">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtState" runat="server" Text='<%# Bind("State") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                           <ItemTemplate>  
                                <asp:Label ID="Label6" runat="server" Text='<%# Bind("State") %>'></asp:Label>  
                            </ItemTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="Pincode">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtPincode" runat="server" Text='<%# Bind("Pincode") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label7" runat="server" Text='<%# Bind("Pincode") %>'></asp:Label>  
                            </ItemTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="Country">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtCountry" runat="server" Text='<%# Bind("Country") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label8" runat="server" Text='<%# Bind("Country") %>'></asp:Label>  
                            </ItemTemplate>
                            </asp:TemplateField>
                        <asp:TemplateField HeaderText="PhoneNumber">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtPhoneNumber" runat="server" Text='<%# Bind("PhoneNumber") %>'></asp:TextBox> 
                                </EditItemTemplate> 
                            <ItemTemplate>  
                                <asp:Label ID="Label9" runat="server" Text='<%# Bind("PhoneNumber") %>'></asp:Label>  
                            </ItemTemplate>
                            </asp:TemplateField>

  </Columns>

</asp:gridview>
        </div>
    </asp:content>

